project_id = "rfwwyddsrwwegwgspydi"

[functions.fortigate-compliance]
verify_jwt = false

[functions.fortigate-cve]
verify_jwt = false

[functions.register-agent]
verify_jwt = false

[functions.validate-m365-connection]
verify_jwt = false
