
ALTER TABLE m365_required_permissions ADD COLUMN IF NOT EXISTS test_url text;

UPDATE m365_required_permissions SET test_url = CASE permission_name
  WHEN 'User.Read.All' THEN 'https://graph.microsoft.com/v1.0/users?$top=1&$select=id'
  WHEN 'Directory.Read.All' THEN 'https://graph.microsoft.com/v1.0/domains?$top=1'
  WHEN 'Group.Read.All' THEN 'https://graph.microsoft.com/v1.0/groups?$top=1&$select=id'
  WHEN 'Application.Read.All' THEN 'https://graph.microsoft.com/v1.0/applications?$top=1&$select=id'
  WHEN 'AuditLog.Read.All' THEN 'https://graph.microsoft.com/v1.0/auditLogs/directoryAudits?$top=1'
  WHEN 'Organization.Read.All' THEN 'https://graph.microsoft.com/v1.0/organization?$select=id'
  WHEN 'Policy.Read.All' THEN 'https://graph.microsoft.com/v1.0/policies/conditionalAccessPolicies?$top=1'
  WHEN 'IdentityRiskyUser.Read.All' THEN 'https://graph.microsoft.com/v1.0/identityProtection/riskyUsers?$top=1'
  WHEN 'IdentityRiskEvent.Read.All' THEN 'https://graph.microsoft.com/beta/identityProtection/riskDetections?$top=1'
  WHEN 'RoleManagement.ReadWrite.Directory' THEN 'https://graph.microsoft.com/v1.0/roleManagement/directory/roleDefinitions'
  WHEN 'RoleManagement.Read.Directory' THEN 'https://graph.microsoft.com/v1.0/roleManagement/directory/roleDefinitions'
  WHEN 'MailboxSettings.Read' THEN 'https://graph.microsoft.com/v1.0/users?$top=1&$select=id'
  WHEN 'Mail.Read' THEN 'https://graph.microsoft.com/v1.0/users?$top=1&$select=id'
  WHEN 'Sites.Read.All' THEN 'https://graph.microsoft.com/v1.0/sites/root?$select=id'
  WHEN 'Reports.Read.All' THEN 'https://graph.microsoft.com/v1.0/reports/authenticationMethods/userRegistrationDetails?$top=1'
  WHEN 'ServiceHealth.Read.All' THEN 'https://graph.microsoft.com/v1.0/admin/serviceAnnouncement/healthOverviews?$top=1'
  WHEN 'DeviceManagementManagedDevices.Read.All' THEN 'https://graph.microsoft.com/v1.0/deviceManagement/managedDevices?$top=1&$select=id'
  WHEN 'DeviceManagementConfiguration.Read.All' THEN 'https://graph.microsoft.com/v1.0/deviceManagement/deviceConfigurations?$top=1&$select=id'
  WHEN 'SecurityAlert.Read.All' THEN 'https://graph.microsoft.com/v1.0/security/alerts_v2?$top=1&$select=id'
  WHEN 'SecurityEvents.Read.All' THEN 'https://graph.microsoft.com/v1.0/security/alerts?$top=1&$select=id'
  WHEN 'SecurityIncident.Read.All' THEN 'https://graph.microsoft.com/v1.0/security/incidents?$top=1&$select=id'
  WHEN 'AttackSimulation.Read.All' THEN 'https://graph.microsoft.com/v1.0/security/attackSimulation/simulations?$top=1'
  WHEN 'InformationProtectionPolicy.Read.All' THEN 'https://graph.microsoft.com/beta/informationProtection/policy/labels'
  WHEN 'TeamSettings.Read.All' THEN 'https://graph.microsoft.com/v1.0/teams?$top=1&$select=id'
  WHEN 'Channel.ReadBasic.All' THEN 'https://graph.microsoft.com/v1.0/teams?$select=id&$top=1'
  WHEN 'TeamMember.Read.All' THEN 'https://graph.microsoft.com/v1.0/teams?$select=id&$top=1'
  WHEN 'SharePointTenantSettings.Read.All' THEN 'https://graph.microsoft.com/beta/admin/sharepoint/settings'
  WHEN 'Domain.Read.All' THEN 'https://graph.microsoft.com/v1.0/domains?$top=1&$select=id'
  WHEN 'Application.ReadWrite.All' THEN 'https://graph.microsoft.com/v1.0/applications?$top=1&$select=id,keyCredentials'
END
WHERE test_url IS NULL;
